version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: aria2ng-server-1
      APP_PORT: 8080

  server:
    image: hurlenko/aria2-ariang
    container_name: aria2ng
    ports:
      - 8080:8080
    volumes:
      - "/srv/docker-data/Movies/Downloads/:/aria2/data"
      - "${APP_DATA_DIR}/data:/aria2/conf"
    environment:
      - PUID=1000
      - PGID=1000
      - ARIA2RPCPORT=443
    restart: always
